name: Scrape and Post NSE Data

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  scrape-and-post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build the Project
        run: npm run build

      - name: Scrape and Post Gainers
        run: node build/get-data.js gainers ${{ secrets.NPOINT_GAINERS_URL }}

      - name: Scrape and Post Losers
        run: node build/get-data.js losers ${{ secrets.NPOINT_LOSERS_URL }}